version: "3.9"

services:

  pokedb:
    image: docker.io/tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "https://pokemonkg.org/"
    volumes:
      - ./pokemon/db:/data
      - ./pokemon/data:/data/toLoad
    ports:
      - "127.0.0.1:8870:8890"
